openapi: 3.0.0
info:
  title: Simple Prediction Service from a local model.
  version: 1.0.0
paths:
  /:
    post:
      summary: Make a prediction from a list of inputs and a local model.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                inputs:
                  type: array
                  items:
                    type: number
              example: [[4, 5, 6], [14, 15, 16]]
      responses:
        '200':
          description: The prediction result.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
                example: [0, 1]