# Continous deployment from GitHub Action to Azure Function.

name: Deploy the simple-prediction-service to Azure Function App

on:
  push:
    #branches:
    #  - main
  workflow_dispatch:

env:
  APPLICATION_DIRECTORY: 'part-1' # where the application code is located

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-function.outputs.webapp-url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install dependencies
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: pip install -r requirements.txt

      - name: Train the model
        working-directory: ${{ env.APPLICATION_DIRECTORY }}
        run: python training.py

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-function
        with:
          app-name: 'az-fct-python-ml'
          slot-name: 'Production'
          package: ${{ env.APPLICATION_DIRECTORY }}
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_877D017FD0C0459CBF2194A1D36A8C40 }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
